/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Cafe_Management_Systems;

import java.util.Calendar;
import java.util.GregorianCalendar;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Random;

/**
 *
 * @author LENOVO
 */
public class Cafe_Management_System extends javax.swing.JFrame {
    double [] drink = new double[5];
    double [] cake = new double[8];
    double [] cost = new double[3];
    double [] i = new double[12];
    /**
     * Creates new form Cafe_Management_System
     */
    public Cafe_Management_System() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox11 = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jlblTax = new javax.swing.JLabel();
        jlblSubTotal = new javax.swing.JLabel();
        jlblTotal = new javax.swing.JLabel();
        jtxtTax = new javax.swing.JTextField();
        jtxtSubTotal = new javax.swing.JTextField();
        jtxtTotal = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jChkCoffeeCake = new javax.swing.JCheckBox();
        jChkRedVelvet = new javax.swing.JCheckBox();
        jChkBoston = new javax.swing.JCheckBox();
        jChkBlackForest = new javax.swing.JCheckBox();
        jChkLagos = new javax.swing.JCheckBox();
        jChkKilburn = new javax.swing.JCheckBox();
        jChkCarlton = new javax.swing.JCheckBox();
        jChkQueens = new javax.swing.JCheckBox();
        jtxtCoffee = new javax.swing.JTextField();
        jtxtRedVelvet = new javax.swing.JTextField();
        jtxtBoston = new javax.swing.JTextField();
        jtxtBlack = new javax.swing.JTextField();
        jtxtLagos = new javax.swing.JTextField();
        jtxtKilburn = new javax.swing.JTextField();
        jtxtCarlton = new javax.swing.JTextField();
        jtxtQueens = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jBtnTotal = new javax.swing.JButton();
        jBtnReceipt = new javax.swing.JButton();
        jBtnReset = new javax.swing.JButton();
        jBtnExit = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jChkLattle = new javax.swing.JCheckBox();
        jChkEspresso = new javax.swing.JCheckBox();
        jChkIcedLattle = new javax.swing.JCheckBox();
        jChkCappuccino = new javax.swing.JCheckBox();
        jChkIcedCappuccino = new javax.swing.JCheckBox();
        jtxtLattle = new javax.swing.JTextField();
        jtxtEspresso = new javax.swing.JTextField();
        jtxtIcedLattle = new javax.swing.JTextField();
        jtxtCappuccino = new javax.swing.JTextField();
        jtxtIcedCappuccino = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtextReceipt = new javax.swing.JTextArea();
        jPanel10 = new javax.swing.JPanel();
        jlblCostDrinks = new javax.swing.JLabel();
        jlblCostCakes = new javax.swing.JLabel();
        jlblService = new javax.swing.JLabel();
        jtxtCostDrinks = new javax.swing.JTextField();
        jtxtCostCakes = new javax.swing.JTextField();
        jtxtService = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1368, 730));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 76)); // NOI18N
        jLabel1.setText("Cafe Management System");

        jLabel2.setFont(new java.awt.Font("Wingdings", 0, 24)); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1330, 120));

        jCheckBox11.setText("jCheckBox2");
        getContentPane().add(jCheckBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jlblTax.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        jlblTax.setText("Tax");

        jlblSubTotal.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        jlblSubTotal.setText("Sub Total");

        jlblTotal.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        jlblTotal.setText("Total");

        jtxtTax.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtxtTax.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtTax.setText("0");
        jtxtTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTaxActionPerformed(evt);
            }
        });

        jtxtSubTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtxtSubTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtSubTotal.setText("0");
        jtxtSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSubTotalActionPerformed(evt);
            }
        });

        jtxtTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtxtTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtTotal.setText("0");
        jtxtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblTax, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtTax, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(jtxtSubTotal)
                    .addComponent(jtxtTotal))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtTax, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jlblTax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlblSubTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(jtxtSubTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 520, 380, 170));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jChkCoffeeCake.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jChkCoffeeCake.setText("Coffee Cake");
        jChkCoffeeCake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkCoffeeCakeMouseClicked(evt);
            }
        });
        jChkCoffeeCake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkCoffeeCakeActionPerformed(evt);
            }
        });

        jChkRedVelvet.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jChkRedVelvet.setText("Red Velvet Cake");
        jChkRedVelvet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkRedVelvetMouseClicked(evt);
            }
        });

        jChkBoston.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jChkBoston.setText("Boston Cream Pie");
        jChkBoston.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkBostonMouseClicked(evt);
            }
        });
        jChkBoston.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkBostonActionPerformed(evt);
            }
        });

        jChkBlackForest.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jChkBlackForest.setText("Black Forest Cake");
        jChkBlackForest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkBlackForestMouseClicked(evt);
            }
        });
        jChkBlackForest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkBlackForestActionPerformed(evt);
            }
        });

        jChkLagos.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jChkLagos.setText("Lagos Chocolate Cake");
        jChkLagos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkLagosMouseClicked(evt);
            }
        });

        jChkKilburn.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jChkKilburn.setText("Kilburn Chocolate Cake");
        jChkKilburn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkKilburnMouseClicked(evt);
            }
        });
        jChkKilburn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkKilburnActionPerformed(evt);
            }
        });

        jChkCarlton.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jChkCarlton.setText("Carlton Hill Chocolate Cake");
        jChkCarlton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkCarltonMouseClicked(evt);
            }
        });
        jChkCarlton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkCarltonActionPerformed(evt);
            }
        });

        jChkQueens.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jChkQueens.setText("Queen's Prank Chocolate Cake");
        jChkQueens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkQueensMouseClicked(evt);
            }
        });
        jChkQueens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkQueensActionPerformed(evt);
            }
        });

        jtxtCoffee.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jtxtCoffee.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtCoffee.setText("0");
        jtxtCoffee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtCoffeeMouseClicked(evt);
            }
        });

        jtxtRedVelvet.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jtxtRedVelvet.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtRedVelvet.setText("0");
        jtxtRedVelvet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtRedVelvetMouseClicked(evt);
            }
        });

        jtxtBoston.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jtxtBoston.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtBoston.setText("0");
        jtxtBoston.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtBostonMouseClicked(evt);
            }
        });

        jtxtBlack.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jtxtBlack.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtBlack.setText("0");
        jtxtBlack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtBlackMouseClicked(evt);
            }
        });

        jtxtLagos.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jtxtLagos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtLagos.setText("0");
        jtxtLagos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtLagosMouseClicked(evt);
            }
        });

        jtxtKilburn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jtxtKilburn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtKilburn.setText("0");
        jtxtKilburn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtKilburnMouseClicked(evt);
            }
        });

        jtxtCarlton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jtxtCarlton.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtCarlton.setText("0");
        jtxtCarlton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtCarltonMouseClicked(evt);
            }
        });

        jtxtQueens.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jtxtQueens.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtQueens.setText("0");
        jtxtQueens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtQueensMouseClicked(evt);
            }
        });
        jtxtQueens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtQueensActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jChkCarlton, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtCarlton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jChkCoffeeCake, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jChkRedVelvet, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jChkBoston, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jChkBlackForest, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jChkLagos, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jChkKilburn, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jChkQueens))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtCoffee, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtRedVelvet, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtBoston, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtBlack, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtLagos, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtKilburn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtQueens, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChkCoffeeCake)
                    .addComponent(jtxtCoffee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChkRedVelvet)
                    .addComponent(jtxtRedVelvet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jtxtBoston, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jChkBoston)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtBlack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChkBlackForest))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtLagos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChkLagos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtKilburn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChkKilburn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtCarlton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChkCarlton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChkQueens, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtQueens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 380, 380));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jBtnTotal.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jBtnTotal.setText("Total");
        jBtnTotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnTotalMouseClicked(evt);
            }
        });
        jBtnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTotalActionPerformed(evt);
            }
        });

        jBtnReceipt.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jBtnReceipt.setText("Receipt");
        jBtnReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnReceiptActionPerformed(evt);
            }
        });

        jBtnReset.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jBtnReset.setText("Reset");
        jBtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnResetActionPerformed(evt);
            }
        });

        jBtnExit.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jBtnExit.setText("Exit");
        jBtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jBtnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jBtnReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jBtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jBtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 520, 590, 170));

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jChkLattle.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jChkLattle.setText("Lattle");
        jChkLattle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkLattleMouseClicked(evt);
            }
        });
        jChkLattle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkLattleActionPerformed(evt);
            }
        });

        jChkEspresso.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jChkEspresso.setText("Espresso");
        jChkEspresso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkEspressoMouseClicked(evt);
            }
        });
        jChkEspresso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkEspressoActionPerformed(evt);
            }
        });

        jChkIcedLattle.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jChkIcedLattle.setText("Iced Lattle");
        jChkIcedLattle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkIcedLattleMouseClicked(evt);
            }
        });
        jChkIcedLattle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkIcedLattleActionPerformed(evt);
            }
        });

        jChkCappuccino.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jChkCappuccino.setText("Cappuccino");
        jChkCappuccino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkCappuccinoMouseClicked(evt);
            }
        });
        jChkCappuccino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkCappuccinoActionPerformed(evt);
            }
        });

        jChkIcedCappuccino.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jChkIcedCappuccino.setText("Iced Cappuccino");
        jChkIcedCappuccino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkIcedCappuccinoMouseClicked(evt);
            }
        });
        jChkIcedCappuccino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkIcedCappuccinoActionPerformed(evt);
            }
        });

        jtxtLattle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtxtLattle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtLattle.setText("0");
        jtxtLattle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtLattleMouseClicked(evt);
            }
        });
        jtxtLattle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtLattleActionPerformed(evt);
            }
        });

        jtxtEspresso.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtxtEspresso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtEspresso.setText("0");
        jtxtEspresso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtEspressoMouseClicked(evt);
            }
        });

        jtxtIcedLattle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtxtIcedLattle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtIcedLattle.setText("0");
        jtxtIcedLattle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtIcedLattleMouseClicked(evt);
            }
        });

        jtxtCappuccino.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtxtCappuccino.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtCappuccino.setText("0");
        jtxtCappuccino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtCappuccinoMouseClicked(evt);
            }
        });
        jtxtCappuccino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCappuccinoActionPerformed(evt);
            }
        });

        jtxtIcedCappuccino.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtxtIcedCappuccino.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtIcedCappuccino.setText("0");
        jtxtIcedCappuccino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtIcedCappuccinoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jChkLattle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jChkEspresso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jChkIcedLattle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jChkCappuccino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jChkIcedCappuccino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jtxtLattle, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                        .addComponent(jtxtEspresso)
                        .addComponent(jtxtCappuccino)
                        .addComponent(jtxtIcedCappuccino))
                    .addComponent(jtxtIcedLattle, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jChkLattle)
                    .addComponent(jtxtLattle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChkEspresso)
                    .addComponent(jtxtEspresso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChkIcedLattle, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtIcedLattle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jChkCappuccino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxtCappuccino))
                .addGap(23, 23, 23)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChkIcedCappuccino)
                    .addComponent(jtxtIcedCappuccino))
                .addGap(38, 38, 38))
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 340, 340));

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jtextReceipt.setColumns(20);
        jtextReceipt.setRows(5);
        jScrollPane1.setViewportView(jtextReceipt);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 130, 590, 380));

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jlblCostDrinks.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jlblCostDrinks.setText("Cost of Drinks");

        jlblCostCakes.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jlblCostCakes.setText("Cost of Cakes");

        jlblService.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jlblService.setText("Service Charge");

        jtxtCostDrinks.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtxtCostDrinks.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtCostDrinks.setText("0");
        jtxtCostDrinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCostDrinksActionPerformed(evt);
            }
        });

        jtxtCostCakes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtxtCostCakes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtCostCakes.setText("0");
        jtxtCostCakes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCostCakesActionPerformed(evt);
            }
        });

        jtxtService.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtxtService.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtService.setText("1.50");
        jtxtService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtServiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblCostDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblCostCakes, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblService, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtCostCakes, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtCostDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtService, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblCostDrinks)
                    .addComponent(jtxtCostDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblCostCakes)
                    .addComponent(jtxtCostCakes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlblService)
                    .addComponent(jtxtService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 340, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jChkIcedLattleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkIcedLattleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChkIcedLattleActionPerformed

    private void jChkBlackForestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkBlackForestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChkBlackForestActionPerformed

    private void jChkCarltonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkCarltonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChkCarltonActionPerformed

    private void jBtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnResetActionPerformed

       jtxtBlack.setText("0");
       jtxtLagos.setText("0");
       jtxtKilburn.setText("0");
       jtxtCarlton.setText("0");
       jtxtQueens.setText("0");
       jtxtRedVelvet.setText("0");
       jtxtBoston.setText("0");
       jtxtRedVelvet.setText("0");
       jtxtCoffee.setText("0");
       jtxtLattle.setText("0");
       jtxtIcedLattle.setText("0");
       jtxtEspresso.setText("0");
       jtxtCappuccino.setText("0");
       jtxtIcedCappuccino.setText("0");
       jtxtTax.setText("0");
       jtxtSubTotal.setText("0");
       jtxtTotal.setText("0");
       jtxtCostCakes.setText("0");
       jtxtCostDrinks.setText("0");
       jtxtService.setText("0");
       jtextReceipt.setText(null);
       jChkEspresso.setSelected(false);
       jChkBlackForest.setSelected(false);
       jChkBoston.setSelected(false);
       jChkCappuccino.setSelected(false);
       jChkCarlton.setSelected(false);
       jChkCoffeeCake.setSelected(false);
       jChkIcedCappuccino.setSelected(false);
       jChkIcedLattle.setSelected(false);
       jChkKilburn.setSelected(false);
       jChkLagos.setSelected(false);
       jChkLattle.setSelected(false);
       jChkQueens.setSelected(false);
       jChkRedVelvet.setSelected(false);
    }//GEN-LAST:event_jBtnResetActionPerformed

    private void jBtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBtnExitActionPerformed

    private void jBtnReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnReceiptActionPerformed
        // TODO add your handling code here:
        drink[0] = Double.parseDouble(jtxtLattle.getText());
        drink[1] = Double.parseDouble(jtxtIcedLattle.getText());
        drink[2] = Double.parseDouble(jtxtEspresso.getText());
        drink[3] = Double.parseDouble(jtxtCappuccino.getText());
        drink[4] = Double.parseDouble(jtxtIcedCappuccino.getText());
        
        cake[0] = Double.parseDouble(jtxtCoffee.getText());
        cake[1] = Double.parseDouble(jtxtRedVelvet.getText());
        cake[2] = Double.parseDouble(jtxtBoston.getText());
        cake[3] = Double.parseDouble(jtxtBlack.getText());
        cake[4] = Double.parseDouble(jtxtLagos.getText());
        cake[5] = Double.parseDouble(jtxtKilburn.getText());
        cake[6] = Double.parseDouble(jtxtCarlton.getText());
        cake[7] = Double.parseDouble(jtxtQueens.getText());
    
        cost[0] = Double.parseDouble(jtxtTax.getText());
        cost[1] = Double.parseDouble(jtxtSubTotal.getText());
        cost[2] = Double.parseDouble(jtxtTotal.getText());
        //=====================================================================================
        int refs = 1325 + (int) (Math.random()*4238);
        
        //=====================================================================================
        Calendar timer = Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
        tTime.format(timer.getTime());
        SimpleDateFormat Tdate = new SimpleDateFormat("dd-MMM-yyyy");
        Tdate.format(timer.getTime());
       // ====================================================================================
        jtextReceipt.append("\t\n CafeManagement Systems : \n\n" +
             "Reference :\t\t\t" + refs +
                "\n===========================================================================\t"+
                "\nLattle:\t\t\t " + drink [0]+
                "\nIced Lattle:\t\t\t " + drink [1]+
                "\nEspresso:\t\t\t " + drink [2]+
                "\nCappuccino:\t\t\t " + drink [3]+
                "\nIced Cappuccino:\t\t " + drink [4]+
                "\n===========================================================================\t\t" +
                        "\nCoffee:\t\t\t" + cake[0]+
                        "\nRed Velvet Cakes:\t\t" + cake[1]+
                        "\nBoston Cream Pie:\t\t" + cake[2]+
                        "\nBlack Forest Cake:\t\t" + cake[3]+
                        "\nLogos chocolate Cake:\t\t" + cake[4]+
                        "\nKilburn Chocolate Cake:\t\t" + cake[5]+
                        "\nCarlton Hill Chocolate Cake:\t\t" + cake[6]+
                        "\nQueen's Park Chocolate Cake:\t\t" + cake[7]+
                "\n===========================================================================\t"+
                        "\nTax:\t\t\t\t" + cost[0]+ 
                        "\nSub Total:\t\t\t\t" + cost[1]+ 
                        "\nTotal:\t\t\t\t" + cost[2]+ 
                "\n=============================================================================\t"+ 
                        
                       "\nDate: " + Tdate.format(timer.getTime()) +
                       "\tTime: " + tTime.format(timer.getTime()) +
                       "\n\nThank You\n\t" );
    }//GEN-LAST:event_jBtnReceiptActionPerformed
    
    private void jChkLattleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkLattleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChkLattleActionPerformed

    private void jChkEspressoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkEspressoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChkEspressoActionPerformed

    private void jChkCappuccinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkCappuccinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChkCappuccinoActionPerformed

    private void jChkIcedCappuccinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkIcedCappuccinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChkIcedCappuccinoActionPerformed

    private void jtxtLattleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtLattleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtLattleActionPerformed

    private void jBtnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTotalActionPerformed
        // TODO add your handling code here:
        drink[0] = Double.parseDouble(jtxtCostDrinks.getText());
        drink[1] = Double.parseDouble(jtxtCostCakes.getText());
        drink[2] = Double.parseDouble(jtxtService.getText());
     
        double cTotal1 = (drink[0]+drink[1]+ drink[2]) ;
        
        String iTaxTotal = String.format("$ %.2f", cTotal1/100);
        jtxtTax.setText(iTaxTotal);
        
        double subTotal = (cTotal1);
        String isubTotal = String.format("$ %.2f",subTotal);
        jtxtSubTotal.setText(isubTotal);
        
        double allTotal = (cTotal1);
        String iTotal = String.format("$ %.2f", allTotal+ (allTotal/100));
        jtxtTotal.setText(iTotal);
        
        String CostD = String.format("$ %.2f", drink[0]);
        jtxtCostDrinks.setText(CostD);
        
        String CostC = String.format("$ %.2f", drink[1]);
        jtxtCostCakes.setText(CostC);
        
        String Service = String.format("$ %.2f", drink[2]);
        jtxtService.setText(Service);
        
    }//GEN-LAST:event_jBtnTotalActionPerformed

    private void jtxtCostCakesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCostCakesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCostCakesActionPerformed

    private void jtxtCostDrinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCostDrinksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCostDrinksActionPerformed

    private void jtxtServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtServiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtServiceActionPerformed

    private void jtxtTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTaxActionPerformed

    private void jtxtSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSubTotalActionPerformed

    private void jtxtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTotalActionPerformed

    private void jChkLattleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkLattleMouseClicked
       double cLattle = Double.parseDouble(jtxtCostDrinks.getText());
        double Lattle = Double.parseDouble(jtxtLattle.getText());
        double iLattle = 1.49;
        
        if(jChkLattle.isSelected())
        {
            i[0] = (Lattle * iLattle) +cLattle;
            String pDrink = String.format("%.2f", i[0]);
            jtxtCostDrinks.setText(pDrink);
        }
    }//GEN-LAST:event_jChkLattleMouseClicked

    private void jChkEspressoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkEspressoMouseClicked
         double cEspresso = Double.parseDouble(jtxtCostDrinks.getText());
        double Espresso = Double.parseDouble(jtxtLattle.getText());
        double iEspresso = 1.99;
        
        if(jChkEspresso.isSelected())
        {
            i[1] = (Espresso * iEspresso) +cEspresso;
            String pDrink = String.format("%.2f", i[1]);
            jtxtCostDrinks.setText(pDrink);
           
    }                             
    }//GEN-LAST:event_jChkEspressoMouseClicked

    private void jChkIcedLattleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkIcedLattleMouseClicked
        double cIcedLattle = Double.parseDouble(jtxtCostDrinks.getText());
        double IcedLattle = Double.parseDouble(jtxtLattle.getText());
        double iIcedLattle = 1.59;
        
        if(jChkIcedLattle.isSelected())
        {
            i[2] = (IcedLattle * iIcedLattle) +cIcedLattle;
            String pDrink = String.format("%.2f", i[2]);
            jtxtCostDrinks.setText(pDrink);
         
    }                                   
    }//GEN-LAST:event_jChkIcedLattleMouseClicked

    private void jChkCappuccinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkCappuccinoMouseClicked
         double cCappuccino = Double.parseDouble(jtxtCostDrinks.getText());
        double Cappuccino = Double.parseDouble(jtxtLattle.getText());
        double iCappuccino = 2.19;
        
        if(jChkCappuccino.isSelected())
        {
            i[3] = (Cappuccino * iCappuccino) +cCappuccino;
            String pDrink = String.format("%.2f", i[3]);
            jtxtCostDrinks.setText(pDrink);
        } 
      
    }//GEN-LAST:event_jChkCappuccinoMouseClicked

    private void jChkIcedCappuccinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkIcedCappuccinoMouseClicked
         double cIcedCap = Double.parseDouble(jtxtCostDrinks.getText());
         double IcedCappuccino = Double.parseDouble(jtxtLattle.getText());
         double iIcedCappuccino = 1.29;
        
        if(jChkIcedCappuccino.isSelected())
        {
            i[4] = (IcedCappuccino * iIcedCappuccino) +cIcedCap;
            String pDrink = String.format("%.2f", i[4]);
            jtxtCostDrinks.setText(pDrink);  
            
         }
    }//GEN-LAST:event_jChkIcedCappuccinoMouseClicked

    private void jtxtCappuccinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCappuccinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCappuccinoActionPerformed

    private void jChkCoffeeCakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkCoffeeCakeMouseClicked
        // TODO add your handling code here:
        double cCoffeeCakes = Double.parseDouble(jtxtCostCakes.getText()); 
         double CoffeeCakes = Double.parseDouble(jtxtCoffee.getText());
         double iCoffeeCakes = 1.49;
         
         if(jChkCoffeeCake.isSelected())
         {
             i[5] = (CoffeeCakes * iCoffeeCakes + cCoffeeCakes);
             String pCoffeeCakes = String.format("%.2f", i[5]);
             jtxtCostCakes.setText(pCoffeeCakes);
         }
    }//GEN-LAST:event_jChkCoffeeCakeMouseClicked

    private void jChkRedVelvetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkRedVelvetMouseClicked
        // TODO add your handling code here:
         double cRedVelvet = Double.parseDouble(jtxtCostCakes.getText()); 
         double RedVelvet = Double.parseDouble(jtxtRedVelvet.getText());
         double iRedVelvet = 1.39;
         
         if(jChkRedVelvet.isSelected())
         {
             i[6] = (RedVelvet * iRedVelvet + cRedVelvet);
             String pRedVelvet = String.format("%.2f", i[6]);
             jtxtCostCakes.setText(pRedVelvet);
         }
    }//GEN-LAST:event_jChkRedVelvetMouseClicked
 
    
    private void jChkBostonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkBostonMouseClicked
        // TODO add your handling code here:
         double cBoston = Double.parseDouble(jtxtCostCakes.getText()); 
         double Boston = Double.parseDouble(jtxtBoston.getText());
         double iBoston = 1.42;
         
         if(jChkBoston.isSelected())
         {
             i[7] = (Boston * iBoston + cBoston);
             String pBoston = String.format("%.2f", i[7]);
             jtxtCostCakes.setText(pBoston);
         }
    }//GEN-LAST:event_jChkBostonMouseClicked

    private void jChkBlackForestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkBlackForestMouseClicked
        // TODO add your handling code here:
         double cBlackForest = Double.parseDouble(jtxtCostCakes.getText()); 
         double BlackForest = Double.parseDouble(jtxtBlack.getText());
         double iBlackForest = 1.55;
         
         if(jChkBlackForest.isSelected())
         {
             i[8] = (BlackForest * iBlackForest + cBlackForest);
             String pBlackForest = String.format("%.2f", i[8]);
             jtxtCostCakes.setText(pBlackForest);
         }
    }//GEN-LAST:event_jChkBlackForestMouseClicked

    private void jChkLagosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkLagosMouseClicked
        // TODO add your handling code here:
         double cLagos = Double.parseDouble(jtxtCostCakes.getText()); 
         double Lagos = Double.parseDouble(jtxtLagos.getText());
         double iLagos = 1.67;
         
         if(jChkLagos.isSelected())
         {
             i[9] = (Lagos * iLagos + cLagos);
             String pLagos = String.format("%.2f", i[9]);
             jtxtCostCakes.setText(pLagos);
         }
    }//GEN-LAST:event_jChkLagosMouseClicked

    private void jChkKilburnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkKilburnMouseClicked
        // TODO add your handling code here:
          double cKilburn = Double.parseDouble(jtxtCostCakes.getText()); 
          double Kilburn = Double.parseDouble(jtxtKilburn.getText());
          double iKilburn = 1.89;
         
         if(jChkKilburn.isSelected())
         {
             i[10] = (Kilburn * iKilburn + cKilburn);
             String pKilburn = String.format("%.2f", i[10]);
             jtxtCostCakes.setText(pKilburn);
         }
    }//GEN-LAST:event_jChkKilburnMouseClicked

    private void jChkCarltonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkCarltonMouseClicked
        // TODO add your handling code here:
          double cCarlton = Double.parseDouble(jtxtCostCakes.getText()); 
          double Carlton = Double.parseDouble(jtxtCarlton.getText());
          double iCarlton = 1.79;
         
         if(jChkCarlton.isSelected())
         {
             i[11] = (Carlton * iCarlton + cCarlton);
             String pCarlton = String.format("%.2f", i[11]);
             jtxtCostCakes.setText(pCarlton);
         }

    }//GEN-LAST:event_jChkCarltonMouseClicked

    private void jChkQueensMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkQueensMouseClicked
        // TODO add your handling code here:
         double cQueens = Double.parseDouble(jtxtCostCakes.getText()); 
          double Queens = Double.parseDouble(jtxtQueens.getText());
          double iQueens = 1.64;
         
         if(jChkQueens.isSelected())
         {
             i[12] = (Queens * iQueens + cQueens);
             String pQueens = String.format("%.2f", i[12]);
             jtxtCostCakes.setText(pQueens);
         }
    }//GEN-LAST:event_jChkQueensMouseClicked

    private void jChkCoffeeCakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkCoffeeCakeActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_jChkCoffeeCakeActionPerformed

    private void jChkBostonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkBostonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChkBostonActionPerformed

    private void jChkQueensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkQueensActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChkQueensActionPerformed

    private void jtxtQueensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtQueensActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtQueensActionPerformed

    private void jChkKilburnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkKilburnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChkKilburnActionPerformed

    private void jtxtLattleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtLattleMouseClicked
        // TODO add your handling code here:
        jtxtLattle.setText(null);
    }//GEN-LAST:event_jtxtLattleMouseClicked

    private void jtxtEspressoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtEspressoMouseClicked
        // TODO add your handling code here:
          jtxtEspresso.setText(null);
    }//GEN-LAST:event_jtxtEspressoMouseClicked

    private void jtxtIcedLattleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtIcedLattleMouseClicked
        // TODO add your handling code here:
          jtxtIcedLattle.setText(null);

    }//GEN-LAST:event_jtxtIcedLattleMouseClicked

    private void jtxtCappuccinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtCappuccinoMouseClicked
        // TODO add your handling code here:
         jtxtCappuccino.setText(null);
    }//GEN-LAST:event_jtxtCappuccinoMouseClicked

    private void jtxtIcedCappuccinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtIcedCappuccinoMouseClicked
        // TODO add your handling code here:
         jtxtIcedCappuccino.setText(null);
    }//GEN-LAST:event_jtxtIcedCappuccinoMouseClicked

    private void jtxtCoffeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtCoffeeMouseClicked
        // TODO add your handling code here:
         jtxtCoffee.setText(null);

    }//GEN-LAST:event_jtxtCoffeeMouseClicked

    private void jtxtRedVelvetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtRedVelvetMouseClicked
        // TODO add your handling code here:
         jtxtRedVelvet.setText(null);
    }//GEN-LAST:event_jtxtRedVelvetMouseClicked

    private void jtxtBostonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtBostonMouseClicked
        // TODO add your handling code here:
        jtxtBoston.setText(null);
    }//GEN-LAST:event_jtxtBostonMouseClicked

    private void jtxtBlackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtBlackMouseClicked
        // TODO add your handling code here:
          jtxtBlack.setText(null);
    }//GEN-LAST:event_jtxtBlackMouseClicked

    private void jtxtLagosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtLagosMouseClicked
        // TODO add your handling code here:
          jtxtLagos.setText(null);
    }//GEN-LAST:event_jtxtLagosMouseClicked

    private void jtxtKilburnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtKilburnMouseClicked
        // TODO add your handling code here:
         jtxtKilburn.setText(null);
    }//GEN-LAST:event_jtxtKilburnMouseClicked

    private void jtxtCarltonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtCarltonMouseClicked
        // TODO add your handling code here:
         jtxtCarlton.setText(null);
    }//GEN-LAST:event_jtxtCarltonMouseClicked

    private void jtxtQueensMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtQueensMouseClicked
        // TODO add your handling code here:
         jtxtQueens.setText(null);
    }//GEN-LAST:event_jtxtQueensMouseClicked

    private void jBtnTotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTotalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnTotalMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cafe_Management_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cafe_Management_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cafe_Management_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cafe_Management_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cafe_Management_System().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnExit;
    private javax.swing.JButton jBtnReceipt;
    private javax.swing.JButton jBtnReset;
    private javax.swing.JButton jBtnTotal;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jChkBlackForest;
    private javax.swing.JCheckBox jChkBoston;
    private javax.swing.JCheckBox jChkCappuccino;
    private javax.swing.JCheckBox jChkCarlton;
    private javax.swing.JCheckBox jChkCoffeeCake;
    private javax.swing.JCheckBox jChkEspresso;
    private javax.swing.JCheckBox jChkIcedCappuccino;
    private javax.swing.JCheckBox jChkIcedLattle;
    private javax.swing.JCheckBox jChkKilburn;
    private javax.swing.JCheckBox jChkLagos;
    private javax.swing.JCheckBox jChkLattle;
    private javax.swing.JCheckBox jChkQueens;
    private javax.swing.JCheckBox jChkRedVelvet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlblCostCakes;
    private javax.swing.JLabel jlblCostDrinks;
    private javax.swing.JLabel jlblService;
    private javax.swing.JLabel jlblSubTotal;
    private javax.swing.JLabel jlblTax;
    private javax.swing.JLabel jlblTotal;
    private javax.swing.JTextArea jtextReceipt;
    private javax.swing.JTextField jtxtBlack;
    private javax.swing.JTextField jtxtBoston;
    private javax.swing.JTextField jtxtCappuccino;
    private javax.swing.JTextField jtxtCarlton;
    private javax.swing.JTextField jtxtCoffee;
    private javax.swing.JTextField jtxtCostCakes;
    private javax.swing.JTextField jtxtCostDrinks;
    private javax.swing.JTextField jtxtEspresso;
    private javax.swing.JTextField jtxtIcedCappuccino;
    private javax.swing.JTextField jtxtIcedLattle;
    private javax.swing.JTextField jtxtKilburn;
    private javax.swing.JTextField jtxtLagos;
    private javax.swing.JTextField jtxtLattle;
    private javax.swing.JTextField jtxtQueens;
    private javax.swing.JTextField jtxtRedVelvet;
    private javax.swing.JTextField jtxtService;
    private javax.swing.JTextField jtxtSubTotal;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTotal;
    // End of variables declaration//GEN-END:variables
}
